# Generated by Django 4.1.1 on 2022-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="sub_total",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=50),
        ),
    ]
