# Generated by Django 4.1.1 on 2022-09-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_wallet_profit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="sub_total",
            new_name="crypto_quantity",
        ),
        migrations.AddField(
            model_name="wallet",
            name="wallet_value",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=50),
        ),
    ]
