# Generated by Django 4.1.1 on 2022-09-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_rename_sub_total_wallet_crypto_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="crypto_quantity",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="profit",
        ),
    ]
