# Generated by Django 4.1.1 on 2022-09-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_remove_wallet_crypto_quantity_remove_wallet_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="crypto_quantity",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=50),
        ),
    ]
